// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmax_det.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMax_det_CfgInitialize(XMax_det *InstancePtr, XMax_det_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMax_det_Start(XMax_det *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMax_det_IsDone(XMax_det *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMax_det_IsIdle(XMax_det *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMax_det_IsReady(XMax_det *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMax_det_EnableAutoRestart(XMax_det *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMax_det_DisableAutoRestart(XMax_det *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_AP_CTRL, 0);
}

void XMax_det_InterruptGlobalEnable(XMax_det *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_GIE, 1);
}

void XMax_det_InterruptGlobalDisable(XMax_det *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_GIE, 0);
}

void XMax_det_InterruptEnable(XMax_det *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_IER);
    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_IER, Register | Mask);
}

void XMax_det_InterruptDisable(XMax_det *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_IER);
    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMax_det_InterruptClear(XMax_det *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMax_det_WriteReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_ISR, Mask);
}

u32 XMax_det_InterruptGetEnabled(XMax_det *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_IER);
}

u32 XMax_det_InterruptGetStatus(XMax_det *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMax_det_ReadReg(InstancePtr->Axilites_BaseAddress, XMAX_DET_AXILITES_ADDR_ISR);
}

