// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMAX_DET_H
#define XMAX_DET_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmax_det_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMax_det_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMax_det;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMax_det_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMax_det_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMax_det_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMax_det_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMax_det_Initialize(XMax_det *InstancePtr, u16 DeviceId);
XMax_det_Config* XMax_det_LookupConfig(u16 DeviceId);
int XMax_det_CfgInitialize(XMax_det *InstancePtr, XMax_det_Config *ConfigPtr);
#else
int XMax_det_Initialize(XMax_det *InstancePtr, const char* InstanceName);
int XMax_det_Release(XMax_det *InstancePtr);
#endif

void XMax_det_Start(XMax_det *InstancePtr);
u32 XMax_det_IsDone(XMax_det *InstancePtr);
u32 XMax_det_IsIdle(XMax_det *InstancePtr);
u32 XMax_det_IsReady(XMax_det *InstancePtr);
void XMax_det_EnableAutoRestart(XMax_det *InstancePtr);
void XMax_det_DisableAutoRestart(XMax_det *InstancePtr);


void XMax_det_InterruptGlobalEnable(XMax_det *InstancePtr);
void XMax_det_InterruptGlobalDisable(XMax_det *InstancePtr);
void XMax_det_InterruptEnable(XMax_det *InstancePtr, u32 Mask);
void XMax_det_InterruptDisable(XMax_det *InstancePtr, u32 Mask);
void XMax_det_InterruptClear(XMax_det *InstancePtr, u32 Mask);
u32 XMax_det_InterruptGetEnabled(XMax_det *InstancePtr);
u32 XMax_det_InterruptGetStatus(XMax_det *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
