// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmax_det.h"

extern XMax_det_Config XMax_det_ConfigTable[];

XMax_det_Config *XMax_det_LookupConfig(u16 DeviceId) {
	XMax_det_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMAX_DET_NUM_INSTANCES; Index++) {
		if (XMax_det_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMax_det_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMax_det_Initialize(XMax_det *InstancePtr, u16 DeviceId) {
	XMax_det_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMax_det_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMax_det_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

