// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_max_det (
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vsum_1,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vlr_1,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vbt_1,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* out_peaks,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vsum_2,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vlr_2,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vbt_2,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vsum_3,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vlr_3,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vbt_3,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vsum_4,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vlr_4,
ap_fixed<26, 26, (ap_q_mode) 2, (ap_o_mode)3, 0>* vbt_4);
